### ISSUE TITLE
Additional links on login page

### ISSUE THREAD

**Issue by jacobtread** [PocketRelay/Dashboard#4]
## Description

Suggestion by one of PocketRelay's users (GamerClassN7) to add additional links to the dashboard login page to assist users to downloading the client and setting up their game

## Checklist

- [x] Additional links are added to the login page to help users find the downloads they require

**Comment by GamerClassN7** [comment]
Maybe it would be good to show link just when no user inventory or calss is detected == that user never connected to server. In center of empty splace  of UI like many CMS do :)

**Comment by jacobtread** [comment]
Great idea! will add this under the existing message for no inventory
